# Generated by Django 4.2.5 on 2023-11-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='student_info',
        ),
    ]
