# Generated by Django 4.2.5 on 2023-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40)),
                ('course_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
