# Generated by Django 4.2.5 on 2023-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=70)),
                ('Duration', models.CharField(max_length=15)),
                ('Seats', models.IntegerField()),
                ('Fees', models.IntegerField()),
            ],
        ),
    ]
