# Generated by Django 4.2.5 on 2023-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='course',
            field=models.CharField(default='BCA', max_length=30),
        ),
    ]
