# Generated by Django 4.2.7 on 2023-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Duration', models.DurationField()),
                ('Seats', models.IntegerField()),
                ('Fees', models.IntegerField()),
            ],
        ),
    ]
